sonar.projectKey=mern-eks-cicd
sonar.projectName=mern-eks-cicd
sonar.sourceEncoding=UTF-8

sonar.sources=app/backend/src,app/frontend/src
sonar.tests=app/backend/test
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=app/backend/coverage/lcov.info
