sonar.projectKey=mern-eks-cicd
sonar.projectName=mern-eks-cicd
sonar.sourceEncoding=UTF-8

sonar.sources=app/backend/src,app/frontend/src
sonar.tests=app/backend/test
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

# If you use Jest coverage, you can wire this in:
# sonar.javascript.lcov.reportPaths=app/backend/coverage/lcov.info

