apiVersion: v1
kind: Namespace
metadata:
  name: mern
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mern-quota
  namespace: mern
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
