namespace:
  create: true
  name: mern

images:
  frontend:
    repository: bhanu0710/mern-frontend
    tag: stable
  backend:
    repository: bhanu0710/mern-backend
    tag: stable
  mongo: mongo:7

frontend:
  replicas: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi

backend:
  replicas: 2
  corsOrigin: "https://mern.example.com"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

mongodb:
  storage: 5Gi
  auth:
    username: root
    # password set via kubernetes secret — see helm/mern-app/templates/mongodb.yaml for kubectl command

ingress:
  enabled: true
  className: nginx
  host: mern.local
  tls:
    enabled: true
    secretName: mern-tls

hpa:
  enabled: true
  backend:
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 60
  frontend:
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 60
